##CNN + Embed
#col_allocine: "review"
#device: "cuda"
#batch_size: 86
#sentence_size: 67
#colname_allocine: "review"
#embed_dim: 200
#embcnn_nb_filtre: 600
#embcnn_type_filtre:
#  filtre2: 2
#
#embcnn_nb_output: 2
#embcnn_dropout: 0.6
#embcnn_min_freq: 3
#embcnn_n_epochs: 30
#
#embcnn_padded: True